name: Deploy to EC2

on:
  push:
    branches:
      - main  # 배포할 브랜치

jobs:
  deploy:
    name: Deploy Node.js to AWS EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      # - name: Run Tests
      #   run: npm test

      - name: SSH to EC2 and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}

        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            cd /home/ubuntu/Node

            # 최신 코드 pull
            git pull origin main

            # 의존성 설치
            npm install

            # mysql 실행 확인 (안되어 있으면 시작)
            if systemctl is-active --quiet mysql; then
              echo "MySQL is running."
            else
              echo "MySQL is not running. Starting MySQL..."
              sudo systemctl start mysql
            fi

            # elasticsearch 실행 확인 (안되어 있으면 시작)
            if systemctl is-active --quiet elasticsearch; then
              echo "Elasticsearch is running."
            else
              echo "Elasticsearch is not running. Starting Elasticsearch..."
              sudo systemctl start elasticsearch
            fi

            # app 실행 확인 (안되어 있으면 시작) & 무중단 배포
            if pm2 describe "app.js" > /dev/null; then
              pm2 reload all
            else
              pm2 start /home/ubuntu/Node/src/server.js --name "app.js"
            fi

            # 무중단 배포 pm2 확인
            pm2 status
          EOF